#!/bin/bash

set -e -x

name=make
version=4.2.1
sha1=7d9d11eb36cfb752da1fb11bb3e521d2a3cc8830

osname=tiger
osver=10.4

# already installed?
prefix=$HOME/opt/$name-$version
test -e $prefix/.installed && exit 0

# use a pre-built package if available
~/prebuilt/$name/$version/$osname && exit 0

# fetch source
tarball=$name-$version.tar.bz2
~/install/bin/fetch-dist $tarball $sha1

# unpack
~/install/bin/unpack-dist $name-$version $tarball
cd $HOME/tmp/$name-$version

# build
cc=/usr/bin/gcc-4.0
mcpu=$( $HOME/install/bin/mcpu )
cflags="-mmacosx-version-min=$osver -mcpu=$mcpu -Os $cflags"
./configure --prefix=$prefix CC=$cc CFLAGS="$cflags"
nice make

# test
# Note: I'm seeing a few tests fail on Tiger/G3, but the resulting
# 'make' binary seems to work, so I'm tolerating 'make check' to failure.
# Details:
#  - misc/close_stdout fails with 'no tests found!'
#  - output-sync.mk fails with signal 14 and a 30-second timeout.
make check || true

# install
rm -rf $prefix
mkdir -p $prefix
make install
touch $prefix/.installed
env > $prefix/.env

# cleanup
cd ..
rm -rf $name-$version
