#!/bin/bash

set -e -x

name=make
version=4.2.1
tarball=$name-$version.tar.bz2
sha1=7d9d11eb36cfb752da1fb11bb3e521d2a3cc8830

osname=tiger
osver=10.4

# already installed?
prefix=$HOME/opt/$name-$version
test -e $prefix/.installed && exit 0

# use a pre-built package if available
~/prebuilt/$name/$version/$osname && exit 0

# fetch source
~/install/bin/fetch-dist $tarball

# unpack
~/install/bin/unpack-dist $tarball $name-$version $sha1
cd ~/tmp/$name-$version

# build
cc=/usr/bin/gcc-4.0
mcpu=$( ~/install/bin/mcpu )
cflags="-mmacosx-version-min=$osver -mcpu=$mcpu -Os $cflags"
./configure --prefix=$prefix CC=$cc CFLAGS="$cflags"
nice make

# test
# Note: I'm seeing a few tests fail on Tiger (G3 and G4), but the resulting
# 'make' binary seems to work, so I'm tolerating 'make check' to failure.
# Details:
#  - misc/close_stdout fails with 'no tests found!'
#  - output-sync.mk fails with signal 14 and a 30-second timeout.
make check || true

# install
rm -rf $prefix
mkdir -p $prefix
make install
touch $prefix/.installed
env > $prefix/.env

# install symlinks
~/install/$name/$version/symlink

# make a pre-built package
~/install/bin/make-package $name $version $osname

# cleanup
rm -rf ~/tmp/$name-$version
