#!/bin/bash

set -e -x

source $( dirname $0 )/common

osname=tiger
osver=10.4

deps=$( cat << EOF
xz/5.2.5
gmp/6.2.0
EOF
)

# install deps
for dep in $deps
do
    ~/install/$dep/$osname
done

# already installed?
test -e $prefix/.installed && exit 0

# use a pre-built package if available
~/prebuilt/$name/$version/$osname && exit 0

# fetch source
~/install/bin/fetch-dist $tarball

# unpack
~/install/bin/unpack-dist $tarball $name-$version $sha1
cd ~/tmp/$name-$version

# build
cc=/usr/bin/gcc-4.0
mcpu=$( ~/install/bin/mcpu )
cflags="-mmacosx-version-min=$osver -mcpu=$mcpu -Os $cflags"
./configure \
    --prefix=$prefix \
    --with-gmp=$HOME/opt/gmp-6.2.0 \
    CC=$cc \
    CFLAGS="$cflags"
nice make

# test
make check

# install
rm -rf $prefix
mkdir -p $prefix
make install
touch $prefix/.installed
env > $prefix/.env

# make a pre-built package
~/install/bin/make-package $name $version $osname

# cleanup
rm -rf ~/tmp/$name-$version
