#!/bin/bash

set -e -x

name=make
version=4.2.1
osname=leopard

mcpu=$( ~/install/bin/mcpu )
if test $mcpu == "7400" ; then
sha1=FIXME
elif test $mcpu == "970" ; then
sha1=2d0c0a12274474d0838d2d7f25226dab6b860d68
else
exit 1
fi

~/prebuilt/bin/fetch-package $name $version $osname
~/prebuilt/bin/unpack-package $name-$version.tgz $name-$version $sha1
~/install/$name/$version/symlink
