#!/bin/bash

set -e -x

name=make
version=4.2.1
osname=leopard

mcpu=$( ~/install/bin/mcpu )
if test $mcpu == "7400" ; then
sha1=TODO
elif test $mcpu == "970" ; then
sha1=2fd48e6c1c3c319c2d7bc3ed9d74eacaa27efe27
else
exit 1
fi

~/prebuilt/bin/fetch-package $name $version $osname
~/prebuilt/bin/unpack-package $name-$version.tgz $name-$version $sha1
~/install/$name/$version/symlink
