#!/bin/bash

set -e -x

name=make
version=4.2.1
osname=tiger

mcpu=$( ~/install/bin/mcpu )
if test $mcpu == "750" ; then
sha1=17fe95abce0488abf9646192f493e0666ba3e74a
elif test $mcpu == "7400" ; then
sha1=3e018f489d5071a4be87fda8c1600ecafc0391cc
else
exit 1
fi

~/prebuilt/bin/fetch-package $name $version $osname
~/prebuilt/bin/unpack-package $name-$version.tgz $name-$version $sha1
~/install/$name/$version/symlink
