#!/bin/bash

set -e -x

name=lzop
version=1.04
tarball=$name-$version.tar.gz
sha1=4924676a9bae5db58ef129dc1cebce3baa3c4b5d

osname=leopard
osver=10.5

deps=$( cat << EOF
lzo/2.10
EOF
)

# install deps
for dep in $deps
do
    ~/install/$dep/$osname
done

# already installed?
prefix=$HOME/opt/$name-$version
test -e $prefix/.installed && exit 0

# use a pre-built package if available
~/prebuilt/$name/$version/$osname && exit 0

# fetch source
~/install/bin/fetch-dist $tarball

# unpack
~/install/bin/unpack-dist $tarball $name-$version $sha1
cd ~/tmp/$name-$version

# build
cc=/usr/bin/gcc-4.2
mcpu=$( ~/install/bin/mcpu )
cflags="-mmacosx-version-min=$osver -mcpu=$mcpu -Os $cflags"
./configure \
    --prefix=$prefix \
    CPPFLAGS=-I$HOME/opt/lzo-2.10/include \
    LDFLAGS=-L$HOME/opt/lzo-2.10/lib \
    CC=$cc \
    CFLAGS="$cflags"
nice make V=1

# test
make check

# install
rm -rf $prefix
mkdir -p $prefix
make install
touch $prefix/.installed
env > $prefix/.env

# install symlinks
~/install/$name/$version/symlink

# make a pre-built package
~/install/bin/make-package $name $version $osname

# cleanup
rm -rf ~/tmp/$name-$version
